services:
  new-aggregator:
    image: new-aggregator-build
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
      - '${VITE_PORT:-5176}:${VITE_PORT:-5176}'
    environment:
      APP_ENV: local
      WWWUSER: '${WWWUSER}'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - './backend:/var/www/html'
    env_file:
      - ./envs/backend.env
    networks:
      - chistel
    depends_on:
      - mysql
      - redis

  scheduler:
    command: /scripts/scheduler.sh
    image: new-aggregator-build
    container_name: news-aggregator-scheduler
    #command: php artisan schedule:work
    stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - ./backend/docker/scripts:/scripts
      - './backend:/var/www/html'
    env_file:
      - ./envs/backend.env
    networks:
      - chistel

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        VITE_APP_BACKEND_ADDRESS: 'http://localhost:80/api'
    ports:
      - "3000:3000"
    environment:
      WWWUSER: '${WWWUSER}'
      VITE_APP_BACKEND_ADDRESS: 'http://localhost:80/api'
    volumes:
      - ./frontend:/app

  mysql:
    container_name: news-aggregator-mysql
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${MYSQL_DB_DATABASE}'
      MYSQL_USER: '${MYSQL_DB_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      #- './backend/docker/mysql:/var/lib/mysql'
      - 'cdev-mysql:/var/lib/mysql'
      - './backend/docker/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - chistel
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  redis:
    container_name: news-aggregator-redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'cdev-redis:/data'
    networks:
      - chistel
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  mailpit:
    container_name: news-aggregator-mailpit
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - chistel

networks:
  chistel:
    driver: bridge
volumes:
  cdev-mysql:
    driver: local
  cdev-redis:
    driver: local

