#!/usr/bin/env bash


#wait_for_mysql() {
#  local retries=30
#  local wait=2
#
#  echo "Waiting for MySQL to be ready..."
#  while ! docker exec news-aggregator-mysql mysqladmin ping -h"mysql" --silent; do
#    retries=$((retries - 1))
#    if [ "$retries" -le 0 ]; then
#      echo "Error: MySQL is not ready after multiple attempts."
#      exit 1
#    fi
#    sleep "$wait"
#  done
#  echo "MySQL is ready!"
#}


# Build containers
./docker/start build --no-cache

# Start containers
./docker/start up -d

# Run composer install
./docker/start composer install

sleep 4

./docker/start artisan migrate

sleep 3

./docker/start artisan db:seed

cd frontend || { echo "Error: 'frontend' directory not found."; exit 1; }

npm install

echo "News aggregator setup complete"
